# -*- coding: utf-8 -*-
"""saisandeshk_a1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fInbEk4Y8RTY00xIl0ITLeCYcZXvdm7C

## DS256 - Scalable Systems for Data Science | Jan 2026
# Assignment 1: LLM Data Preprocessing Pipeline with Apache Spark

#### Posted on: 2026-02-07
#### Deadline: 2026-03-01 (For code submission), 2026-03-08 (For scalability/report)
#### Maximum Points: 100 (50 for code correctness, 50 for scalability/report)

### Changelog:
----
* v1: Initial release of questions.
* v2: Fixed validations; added detailed instructions.
* v3: Fixed import versions; updated record numbers and timings; updated instructions for steps 5b and 6; updated reference outputs for all steps.

### Common Instructions
----
* You must ONLY edit cells and regions within those cells that allow changes. **DO NOT MODIFY other cells**. This can cause the evaluation script to break and you **WILL** be penalized or get **ZERO** points.
* You MUST NOT use the string **###!@** anywhere in your code or comments. We will be using this special substring for pattern matching during evaluations.
* You may declare **all** your valid imports and user-defined functions in the cells that are provided. Otherwise, all parts of your answer must remain between the space provided for the solution to each question.
* You must only use transformations and actions over Spark DataFrames, Spark SQL, and Spark RDDs to solve the assignment (**Spark Core**). You **MUST NOT** use MLLib, etc, unless specified.
 <!-- * https://spark.apache.org/docs/latest/api/python/reference/pyspark.html#rdd-apis -->
* Most of your processing to solve the problem should be done **within Spark**. Minimal post processing may be done in the Python driver code.
* You **must not** use Numpy, Scipy, etc. within the **driver** code. But you may use standard Python libraries as part of lambda expressions or functions passed to Spark transformations and actions.
<!-- * You must not use the default statistics operation (RDD.stats()) available in the **Spark Numeric RDD**. -->
* Our evaluations will include **alternate input WARC files** that have the same format but different contents/sizes.
* We have provided **reference outputs** and the **number of output records** for the test inputs for the **small** input set. You can use these to verify the correctness of your solutions. We have also provided **reference execution time** taken by each step on **Colab**.
* The evaluation will be done by passing clean reference inputs to each problem, i.e., even if one of the steps fails, we will evaluate the subsequent steps on the reference output from the previous steps.
* You will get **bonus** marks if the *end-to-end pipeline* works correctly and also if your runtime is faster than the *reference execution time* we have provided.
* 50% of the assessment goes towards your scalability evaluation, plots and detailed report. You **must** complete and submit the code for correctness evaluation by the first deadline and spend time on the experiments, analysis of performance and the report for the second deadline.
* The report should include a detailed analysis of the strong and weak scaling behavior of the individual steps as well as the end-to-end pipeline supported by experimental evidence and plots.
* **NOTE (Trigger Warning):** *Part of the assignment involves filtering out banned URLs. Kindly take care when processing this data as it may have sensitive words that are (by definition) not polite and potentially upsetting.*
<br>

### **IMPORTANT:** Academic Integrity
----
 The assignment must be completed by yourself and your teammate without any assistance from others or from online sources, ChatGPT, Copilot, etc. Taking online help for standard API references or clearing simple doubts on Python/Spark is allowed. If **any cases of plagiarism are detected, you may get a failing grade in the course and/or be reported to the Institute for further action**. Please follow IISc's Policy on Academic Integrity, https://iisc.ac.in/about/student-corner/academic-integrity/ .

### Submission Guidelines
----

1. Copy the **LATEST** template notebook to your local Google drive. Change the name of the notebook to **assignment1_sol.ipynb**. Proceed to complete the assignment within colab.
2. Make edits only in cells and regions that are clearly marked for modification. **Do not change the template in any other way**. We will be automatically parsing relevant cells and functions during grading. If these instructions are not followed (e.g., even an extra space in an unauthorized part), you can get a **zero** for the Assignment.
3. After you've solved the questions, verify that the output that you generate passes the **validation check** of the data types, and matches the reference outputs that are provided for the sample inputs. Note that for **floats** (if relevant), only the first 3 digits of precision will be checked, but you should not make any changes to the default precision in your code. If the output data type is not valid as specified, you will get a zero for that problem.
4. Each of the problems should take no longer than 5x the reference time as given for our reference outputs. If it takes longer, the problem will not be evaluated.
5. When you are ready to submit the assignment, download the notebook as a **(.py)** file to your local machine. You can do so by going to **File > Download > Download (.py)** in your colab environment.
6. By the first deadline, upload the **pranjalnaman_a1.py** file to Moodle Assignment-1-Code, if your or your teammmate's IISc email address is pranjalnaman@iisc.ac.in. *Upload only 1 file per team!*
7. By the second deadline, upload **pranjalnaman_a1.pdf** to Moodle Assignment-1-Report.

### Overview
----
This assignment implements a complete **LLM Data Preprocessing Pipeline** using Apache Spark on a YARN cluster. The pipeline processes raw Common Crawl WARC data through 5 steps to produce clean, tokenized training data suitable for Large Language Model training.

### Pipeline Steps
| Step | Name | Description |
|-------|------|-------------|
| 1 | Warc to Parquet | Convert the warc files to parquet (5%) |
| 2 | Ingestion / Filter | Load WARC parquet files and filter blacklisted domains (15%) |
| 3 | Extraction | Extract clean text from HTML using Trafilatura (15%) |
| 4 | Language ID | Filter to English-only documents using FastText (15%) |
| 5 | Deduplication | Remove near-duplicate documents using MinHash LSH (30%) |
| 6 | Tokenization | Convert text to token sequences for model training (20%) |

### Common Instructions
----
* You must ONLY edit cells and regions within those cells that allow changes. **DO NOT MODIFY** cells marked with `DO NOT MODIFY`.
* All processing should be done **within Spark** using DataFrames, RDDs, and Spark SQL.
* Ensure your virtual environment Python is accessible to all YARN worker nodes.
"""

# ======== DO NOT MODIFY ===========
!pip install pyspark==4.0.2
!pip install warcio==1.7.5
!pip install fasttext==0.9.3
!pip install trafilatura==1.12.2
!pip install lxml==5.4.0
!pip install numpy==1.26.4

# ======== DO NOT MODIFY ===========
import sys
import os
import subprocess
import time
import pyspark
from pyspark import SparkFiles
import fasttext
import hashlib

from urllib.parse import urlparse
from pyspark.sql.types import StructType, StructField, StringType, BinaryType
from pyspark.ml.feature import MinHashLSH
from pyspark.ml.linalg import Vectors, VectorUDT
from pyspark.sql import Window
from pyspark.sql import SparkSession
from google.colab import drive
from warcio.archiveiterator import ArchiveIterator

# ======== DO NOT MODIFY ===========
drive.mount('/content/drive', force_remount=True)

# ======== DO NOT MODIFY ===========
BASE_DIR = '/content/drive/Shareddrives/ds256-2026-public/assignment_1/small' # we will change this to large. You may test with `small` and `medium`.
BLACKLIST_DOMAINS_DIR = '/content/drive/Shareddrives/ds256-2026-public/assignment_1/blacklist_domains'
FASTTEXT_MODEL_BIN = '/content/drive/Shareddrives/ds256-2026-public/assignment_1/lid.176.bin'
PARQUET_DIR = '/content/drive/MyDrive/Final/step1_checkpoint' #TODO: Change it to a dir on your drive

# ======= DO NOT MODIFY ============
spark = (
    SparkSession.builder
    .appName("LLMSpark")
    .master("local[*]")
    .config("spark.sql.execution.arrow.pyspark.enabled", "true")
    .config("spark.driver.memory", "8g")
    .config("spark.executor.memory", "8g")
    .config("spark.driver.maxResultSize", "4g")
    .config("spark.sql.shuffle.partitions", "8")
    .config("spark.memory.fraction", "0.8")
    .getOrCreate()
)

"""## Verify the warc files are readable"""

# ======= DO NOT MODIFY ============
os.listdir(BASE_DIR)

# ===== SCHEMA VALIDATORS FOR EACH STEP (DO NOT MODIFY) =====

# STEP 2 Output Schema Validator
STEP_2_SCHEMA = {
    'warc_id': 'string',
    'url': 'string',
    'date': 'string',
    'html_content': 'string'
}

# STEP 3 Output Schema Validator
STEP_3_SCHEMA = {
    'warc_id': 'string',
    'url': 'string',
    'date': 'string',
    'extracted_text': 'string'
}

# STEP 4 Output Schema Validator (same as STEP 3)
STEP_4_SCHEMA = {
    'warc_id': 'string',
    'url': 'string',
    'date': 'string',
    'extracted_text': 'string'
}

# STEP 5 Output Schema Validator (same as STEP 3)
STEP_5_SCHEMA = {
    'warc_id': 'string',
    'url': 'string',
    'date': 'string',
    'extracted_text': 'string'
}

# STEP 6 Output Schema Validator
STEP_6_SCHEMA = {
    'warc_id': 'string',
    'tokens': 'array<int>',
    'attention_mask': 'array<int>'
}

# ===== SCHEMA VALIDATORS FOR EACH STEP (DO NOT MODIFY) =====

from pyspark.sql import SparkSession
from pyspark.sql import functions as F
from pyspark.sql.types import *
from pyspark.storagelevel import StorageLevel

# Helper for schema validation (DO NOT MODIFY)
def validate_schema(df, expected_columns):
    """Verifies that the dataframe contains the required columns with correct types."""
    df_cols = {f.name: f.dataType.simpleString() for f in df.schema.fields}
    missing = []
    for col, type_str in expected_columns.items():
        if col not in df_cols:
            missing.append(f"{col} (missing)")
        elif type_str not in df_cols[col]:
            pass
    if missing:
        raise ValueError(f"Schema Validation Failed. Issues: {missing}")
    else:
        return

def validate_step_schema(df, step_num):
    """Validate DataFrame schema for a specific step."""
    schemas = {
        2: STEP_2_SCHEMA,
        3: STEP_3_SCHEMA,
        4: STEP_4_SCHEMA,
        5: STEP_5_SCHEMA,
        6: STEP_6_SCHEMA,
    }
    expected = schemas.get(step_num, {})
    validate_schema(df, expected)
    print(f"✓ STEP {step_num} schema validation passed!")

"""---
---
## Your Code Edits Start from Here
---
### Common Imports and Functions

List imports and functions that are used across different questions in these sections.
"""

#######################################
###!@0.1 START COMMON USER IMPORTS
#######################################
## Specify valid imports, if any, for ALL your answers  ==========
## start your edits here =================

import trafilatura
from pyspark import StorageLevel
import regex as re

## end your edits here =================
###!@0.1 END COMMON USER IMPORTS

#######################################
###!@0.2 START COMMON USER FUNCTIONS
#######################################
## Specify user defined functions, if any, used by multiple answers   =====
## start your edits here =================

_fasttext_model = None

def get_fasttext_model():
  """
  1) Loads the FastText Language ID model from the workers local copy of the file (placed there by sc.addFile) on the very first call,
  then caches it in the _fasttext_model for subsequent calls on the same worker.
  2) why global: python requires "global" to *assign* to an outer-scope variable inside a function; without it, Python creates a new local variable and the cached value is thrown away
  after each call.
  """
  # 2
  global _fasttext_model
  # 1
  if _fasttext_model is None:
    # SparkFiles.get(filename) returns the local Disk Path where spark copied the file on THIS worker - pass only the filename, not the Drive Path.
    local_path = SparkFiles.get('lid.176.bin')
    _fasttext_model = fasttext.load_model(local_path)
  return _fasttext_model

## end your edits here =================
###!@0.2 END COMMON USER FUNCTIONS

"""## STEP 1: Convert the warc files to parquet ***(5 points)***
----

### Objective
Ingest raw WARC data from the HDFS file system (Google Drive in this Colab Notebook), parse the records to extract HTML content, and save the result as a partitioned Parquet dataset.

The function returns nothing. It just writes the parquet files to OUTPUT_DIR.

### Reference execution time on Colab & Output Record Count on *Small* Dataset
#### Time: `310 seconds`
#### # of records: `43,334 records`

### Guidelines
1. List Files: Retrieve the list of .warc files from the BASE_DIR directory.
2. Stream each WARC file.
3. Parse records using warcio.ArchiveIterator.
4. Filter for records where rec_type is 'response' and Content-Type contains 'html'.
5. Write to Parquet: Save the DataFrame to OUTPUT_DIR in Parquet format, partitioned by the original WARC filename.

***The DataFrame should have the output schema defined below.***
### Parquet DataFrame Schema
| Column | Type | Description |
|--------|------|-------------|
| warc_id | string | Unique WARC record identifier |
| url | string | Source URL |
| date | string | Crawl timestamp |
| html_content | string | Raw HTML content |
| warc_filename | string | The name of the source WARC file (used for partitioning)
"""

#######################################
###!@1 START ANSWER STEP 1

### Q1 ###################################################

def step_1_warc_to_parquet():
    """
    Convert warc files at BASE_DIR and place the parquet file in PARQUET_DIR
    """
    ## start your edits here  =================

    # define schema
    schema = StructType([
        StructField("warc_id", StringType(), nullable=True),
        StructField("url", StringType(), nullable=True),
        StructField("date", StringType(), nullable=True),
        StructField("html_content", StringType(), nullable=True),
        StructField("warc_filename", StringType(), nullable=True)
    ])

    warc_paths = [os.path.join(BASE_DIR, f) for f in os.listdir(BASE_DIR) if f.endswith('.warc')]

    def parse_warc_file(filepath):
      # generator that streams one WARC file and yeilds one tuple per valid HTML response record
      filename = os.path.basename(filepath)

      with open(filepath, "rb") as f:
        # streams record by record
        for record in ArchiveIterator(f):

          if record.rec_type != 'response':
            continue

          content_type = record.http_headers.get_header('Content-Type') or ''
          if 'html' not in content_type.lower():
            continue

          html_content = record.content_stream().read().decode(
              'utf-8', errors='replace'
          )

          # YIELD (not append + return): Spark pulls this one record, then immediately asks for the next - memory is freed between yields
          yield (
              record.rec_headers.get_header('WARC-RECORD-ID'),
              record.rec_headers.get_header('WARC-Target-URI'),
              record.rec_headers.get_header('WARC-Date'),
              html_content,
              filename,
          )

    rdd = spark.sparkContext.parallelize(warc_paths, numSlices=len(warc_paths))

    records_rdd = rdd.flatMap(parse_warc_file)

    df = spark.createDataFrame(records_rdd, schema=schema)

    df.write.partitionBy('warc_filename').parquet(PARQUET_DIR, mode='overwrite')

    ## end your edits here  =================


###!@1 END ANSWER STEP 1

"""## STEP 2: Data Ingestion & Domain Filtering ***(15 points)***
----


### Objective
Load raw WARC data from parquet files and filter out records from blacklisted domains.

### Reference execution time on Colab & Output Record Count on *Small* Dataset
#### Time: `35 seconds`
#### # of records: `40,985 records`

### Input
- `input_path`: HDFS (Colab for this notebook) path to parquet files containing WARC records

### Processing Steps
1. **Construct Domain Blacklist**:
    - Recursively walk the `blacklist_root_dir`.
    - Identify files named `domains` or `urls`.
    - Read each file line-by-line, stripping whitespace.
    - Ignore lines starting with `#` (comments).
    - The aforementioned steps are guidelines. Ultimately we want the ouput in the format described below.
    - Output can look like - `{'altabu-db1.blogspot.hu',
 'biwaisms-putesdefoncees.blogspot.cz',
 'kamilla18.blogspot.jp',
 'batorsparadise.blogspot.pt', ...}`
2. Extract domain from URL using regex.
3. Drop the records where domain and/or subdomains matches blacklist.


### Output Schema
| Column | Type | Description |
|--------|------|-------------|
| warc_id | string | Unique WARC record identifier |
| url | string | Source URL |
| date | string | Crawl timestamp |
| html_content | string | Raw HTML content |

### Expected Output Example (Step 2)
```
root
|-- warc_id: string (nullable = true)
|-- url: string (nullable = true)
|-- date: string (nullable = true)
|-- html_content: string (nullable = true)

[Stage 109:>                                                        (0 + 1) / 1]
+--------------------+--------------------+--------------------+--------------------+
|             warc_id|                 url|                date|        html_content|
+--------------------+--------------------+--------------------+--------------------+
|<urn:uuid:ed46a75...|https://www.futur...|2025-12-04T20:34:05Z|<!DOCTYPE html><h...|
|<urn:uuid:9fb9dc9...|https://amotion.t...|2025-12-04T19:35:27Z|\n\n<!DOCTYPE htm...|
|<urn:uuid:98bada1...|https://www.fuzzy...|2025-12-04T20:30:52Z|<!DOCTYPE html>\n...|
|<urn:uuid:7149527...|https://amp.rtve....|2025-12-04T19:49:05Z|\n  <!DOCTYPE htm...|
|<urn:uuid:423fa66...|https://www.fwg-p...|2025-12-04T19:25:30Z|<!DOCTYPE html>\n...|
+--------------------+--------------------+--------------------+--------------------+
only showing top 5 rows

Schema Validation Passed!
✓ Step 2 schema validation passed!
"""

#######################################
###!@2 START ANSWER STEP 2

### Q2 ###################################################

def load_blacklist_categories():
    """
    Reads domains from the blacklist directory structure.
    Returns a set of domains for fast lookup.
    """
    print("Loading blacklist categories...")
    blacklisted_domains = set()

    ## start your edits here  =================

    # use os.walk() to visit every sub-folder beneath the BLACKLIST_DOMIAINS_DIR recursively:
    for dirpath, dirnames, filenames in os.walk(BLACKLIST_DOMAINS_DIR):
      for filename in filenames:
        if filename not in ('domains', 'url'): # only process files named 'domains' or 'urls' and ignore any other files present
          continue

        filepath = os.path.join(dirpath, filename)
        with open(filepath, 'r', errors='ignore') as f:
          for line in f:
            line = line.strip() # remove leading / trailing whitespace and newlines

            if not line or line.startswith('#'):
              continue # skip blank lines and comment lines

            blacklisted_domains.add(line)

    ## end your edits here  =================

    return blacklisted_domains

def step_2_ingestion():
    """
    Load parquet files and filter out blacklisted domains.
    Returns DataFrame with columns: warc_id, url, date, html_content
    """

    blacklisted_domains = load_blacklist_categories()

    ## start your edits here  =================

    # broadcast the blacklist set to all the spark workers and with broadcast(), each worker receives one efficient cached copy in memory.
    broadcast_blacklist = spark.sparkContext.broadcast(blacklisted_domains)

    def is_blacklisted(domain) -> bool:
    # returns True if domain exactly matches or is a subdomain of any entry in the broadcast blacklist set.

      if not domain:
        return False

      # access the broadcasted set on 'this' worker via .value
      bl = broadcast_blacklist.value

      if domain in bl: # domain check
        return True

      # sub-domain check
      parts = domain.split('.')
      for i in range(1, len(parts)-1):
        parent = '.'.join(parts[i:])
        if parent in bl:
          return True

      return False

    # register as a spark UDF returning boolean. (True = Blacklisted = Drop)
    is_blacklisted_udf = F.udf(is_blacklisted, BooleanType())

    # load parquet written in step-1
    df = spark.read.parquet(PARQUET_DIR)

    # extract hostname from URL
    df = df.withColumn(
        'domain',
        F.regexp_extract(F.col('url'), r'https?://([^/?\s]+)', 1)
    )

    # filter out the blacklisted domains and due to boolen logic, we keep rows where is_blacklisted returns False
    df_filtered = df.filter(~is_blacklisted_udf(F.col('domain')))

    output_df = df_filtered.drop('domain') # drop the 'domain' as per schema

    ## end your edits here  =================

    return output_df

###!@2 END ANSWER STEP 2

"""---
## Step 3: Text Extraction ***(15 points)***
----

### Objective
Extract clean, readable text content from raw HTML using the Trafilatura library.

### Reference execution time on Colab & Output Record Count on *Small* Dataset
#### Time: `2240 seconds`
#### # of records: `39,984 records`

### Input
- DataFrame with `html_content` column (from Step 2)

### Processing Steps (Guidelines)
1. Apply `trafilatura` extraction. You can exclude comments, include tables, and have `no_fallback=False`
2. Drop records that cannot be processed by `trafilatura`.
3. It is possible that `trafilatura` returns nothing. Drop such records, i.e., only records with valid extracted text must be retained.


### Output Schema
| Column | Type | Description |
|--------|------|-------------|
| warc_id | string | Unique WARC record identifier |
| url | string | Source URL |
| date | string | Crawl timestamp |
| extracted_text | string | Clean text extracted from HTML |

### Expected Output Example (Step 3)
```
root
 |-- warc_id: string (nullable = true)
 |-- url: string (nullable = true)
 |-- date: string (nullable = true)
 |-- extracted_text: string (nullable = true)

[Stage 117:>                                                        (0 + 1) / 1]
+--------------------+--------------------+--------------------+---------------------------+
|             warc_id|                 url|                date|             extracted_text|
+--------------------+--------------------+--------------------+---------------------------+
|<urn:uuid:51e562d...|https://www.viagr...|2025-12-04T19:37:35Z|产品分类\nProducts相关文...|
|<urn:uuid:9422649...|http://www.elolit...|2025-12-04T20:43:27Z|       Confinarse, encer...|
|<urn:uuid:e4642c3...|https://www.viapi...|2025-12-04T20:27:35Z|       Warenkorb ist lee...|
|<urn:uuid:85aa3aa...|http://www.empren...|2025-12-04T20:47:21Z|       ¿Qué es el delito...|
|<urn:uuid:7c4b999...|https://www.vibar...|2025-12-04T19:39:43Z|       317 Products\nΚαν...|
+--------------------+--------------------+--------------------+---------------------------+
only showing top 5 rows

Schema Validation Passed!
✓ Step 3 schema validation passed!

```
"""

#######################################
###!@3 START ANSWER STEP 3

### Q3 ###################################################

def step_3_extraction(input_df):
    """
    Args:
        input_df: DataFrame with 'html_content' (string).
    Returns:
        DataFrame: With 'extracted_text' (string) replacing html_content.
    """
    ## start your edits here  =================

    # define the function to extract the text using trafilatura
    def extract_text(html):
      # return None if not html
      if html is None:
        return None

      try:
        result = trafilatura.extract(html, include_comments=False, include_tables=True, no_fallback=False) # based on the instructions
        # check if the result is non-empty
        if result is None or result.strip() == "":
          return None

        return result.strip()

      except Exception:
        return None

    extract_udf = F.udf(extract_text, StringType())

    output_df = (input_df.withColumn("extracted_text", extract_udf(F.col("html_content"))).drop("html_content", "warc_filename")
                          .filter(F.col("extracted_text").isNotNull()).filter(F.col("extracted_text") != ""))

    ## end your edits here  =================

    return output_df

###!@3 END ANSWER STEP 3

"""---
## STEP 4: Language Identification ***(15 points)***
----

### Objective
Filter documents to retain only English content using FastText language identification.

### Reference execution time on Colab & Output Record Count on *Small* Dataset
#### Time: `40 seconds`
#### # of records: `14,288 records`

### Input
- DataFrame with `extracted_text` column (from Step 3)
- `threshold`: Minimum probability for English classification (default: 0.6). We will test your code with different thresholds.

### Processing Steps
1. Predict language for each document (`Fasttext` requires single line inputs. Handle line breaks in extracted text.)
2. Filter to retain only documents classified as English (`__label__en`) with probability ≥ threshold

### Output Schema
Same as input (records that pass the English filter)

### Expected Output Example (Step 4)
```
root
 |-- warc_id: string (nullable = true)
 |-- url: string (nullable = true)
 |-- date: string (nullable = true)
 |-- extracted_text: string (nullable = true)

[Stage 124:>                                                        (0 + 1) / 1]
+--------------------+--------------------+--------------------+--------------------+
|             warc_id|                 url|                date|      extracted_text|
+--------------------+--------------------+--------------------+--------------------+
|<urn:uuid:d119f3d...|https://snapvrs.o...|2025-12-04T20:39:17Z|As solar panels d...|
|<urn:uuid:75d7f1f...|https://fresh-tri...|2025-12-04T20:30:35Z|Diving in Jordan,...|
|<urn:uuid:bb9ce09...|https://snippets....|2025-12-04T21:11:11Z|Are RV campers a ...|
|<urn:uuid:4ed2248...|https://frigidair...|2025-12-04T20:47:04Z|Frigidaire Dryer ...|
|<urn:uuid:b0b3105...|https://soap2day....|2025-12-04T20:50:59Z|Genre\nAction\nAd...|
+--------------------+--------------------+--------------------+--------------------+
only showing top 5 rows

Schema Validation Passed!
✓ Step 4 schema validation passed!
```
"""

#######################################
###!@4 START ANSWER STEP 4

### Q4 ###################################################

def step_4_lang_id(input_df, threshold=0.6):
    """
    Args:
        input_df: DataFrame with 'extracted_text' column.
        threshold: Minimum probability for English classification (default: 0.6).
    Returns:
        DataFrame: English-only documents.
    """

    ## start your edits here  =================

    spark.sparkContext.addFile(FASTTEXT_MODEL_BIN)

    # create a language udf
    def is_english(text):
        # returns True if FastText classifies the text as Englisj with probability >= threshold

        if not text or not text.strip(): # null or white-space text cannot be classified so discard it.
            return False

        # load the model, and we don't have make any other all we already did the function get_fasttext_model()
        model = get_fasttext_model()

        clean_text = text.replace('\n', ' ').replace('\r', ' ').strip() # clean based on how FastText treats documents

        result = model.predict(clean_text) # returns: (tuple, array of probabilities)

        top_label = result[0][0]
        top_prob  = float(result[1][0])

        # ensure both conditions are satisfied
        return (top_label == '__label__en') and (top_prob >= threshold)

    is_english_udf = F.udf(is_english, BooleanType())

    # keep english documents only
    output_df = input_df.filter(is_english_udf(F.col('extracted_text')))

    ## end your edits here  =================

    return output_df

###!@4 END ANSWER STEP 4

"""---
## STEP 5: Deduplication ***(30 points)***
----

### Objective
Duplicate records can be detrimental to LLM training and therefore need to be dropped. Here, you will write 2 different deduplication algorithms, one approximate and one exact, and compare the two in your report.

---
## STEP 5a: Near-Duplicate Deduplication ***(15 points)***
----

### Objective
Remove near-duplicate documents using MinHash Locality-Sensitive Hashing (LSH).

### Reference execution time on Colab & Output Record Count on *Small* Dataset
#### Time: `150 seconds`
#### # of records: `12,808 records`

### Input
- DataFrame with `extracted_text` column (from Step 4)

### Guidelines
1. **Character 5-grams**: Convert text to character-level 5-grams, hash each to a vocabulary index
2. **MinHash Signatures**: Generate 24 MinHash signatures using Spark MLlib's MinHashLSH
3. **Banding**: Split signatures into 8 bands of 3 hashes each for similarity detection
4. **Clustering**: Find similar document pairs with Jaccard distance ≤ 0.5
5. **Filtering**: Keep only the longest document from each cluster

### Configuration
| Parameter | Value | Description |
|-----------|-------|-------------|
| NGRAM_SIZE | 5 | Character n-gram length |
| NUM_HASHES | 24 | Total MinHash signatures |
| NUM_BANDS | 8 | Number of LSH bands |
| VOCAB_SIZE | 2^18 | Hash space size (262,144) |

### Output Schema
Same as input (deduplicated records)

### Expected Output Example (Step 5a)
```
root
 |-- warc_id: string (nullable = true)
 |-- url: string (nullable = true)
 |-- date: string (nullable = true)
 |-- extracted_text: string (nullable = true)

[Stage 155:======================================================>(96 + 1) / 97]
+--------------------+--------------------+--------------------+--------------------+
|             warc_id|                 url|                date|      extracted_text|
+--------------------+--------------------+--------------------+--------------------+
|         warc_id_102|http://example.co...|2025-12-04T21:02:54Z|Machine learning ...|
|         warc_id_103|http://example.co...|2025-12-04T21:02:55Z|Python is a high-...|
|<urn:uuid:caa5d51...|https://www.valte...|2025-12-04T20:38:04Z|Agentforce: The G...|
|<urn:uuid:15335f8...|https://www.vande...|2025-12-04T20:39:07Z|This Cookie Polic...|
|<urn:uuid:b5590de...|http://www.elks.o...|2025-12-04T20:06:13Z|Join the Elks!\nL...|
+--------------------+--------------------+--------------------+--------------------+
only showing top 5 rows

Schema Validation Passed!
✓ Step 5a schema validation passed!
```
"""

#######################################
###!@5a START ANSWER STEP 5a

### Q5a ###################################################
def step_5a_deduplication(input_df):
    """
    Args:
        input_df: English text dataframe.
    Returns:
        DataFrame: Deduplicated dataframe using MinHash LSH.
    """
    ## start your edits here  =================

    def char_ngrams(text):
      if not text:
          return []
      return list(set(text[i:i+5] for i in range(len(text) - 4)))

    char_ngrams_udf = F.udf(char_ngrams, ArrayType(StringType()))

    def extract_bands(hashes):
      if not hashes or len(hashes) != 24:
          return []
      return [f"{i}_{int(hashes[i*3][0])}_{int(hashes[i*3+1][0])}_{int(hashes[i*3+2][0])}" for i in range(8)]

    extract_bands_udf = F.udf(extract_bands, ArrayType(StringType()))

    def get_indices(vec):
      return vec.indices.tolist() if vec else []

    get_indices_udf = F.udf(get_indices, ArrayType(IntegerType()))

    # feature extraction: char 5-grams -> hashing TF -> minhash signatures
    df = input_df.withColumn("ngrams", char_ngrams_udf(F.col("extracted_text"))).withColumn("text_len", F.length(F.col("extracted_text")))
    df = HashingTF(inputCol="ngrams", outputCol="features", numFeatures=2**18).transform(df)
    mh_model = MinHashLSH(inputCol="features", outputCol="hashes", numHashTables=24).fit(df)
    df = mh_model.transform(df)
    df.cache().count()

    # lightweight view with band keys and feature indices
    lite = df.select(
        F.col("warc_id").alias("w_id"),
        F.col("text_len").alias("t_len"),
        extract_bands("hashes").alias("bands"),
        get_indices("features").alias("indices")
    )

    # candidate generation via band matching
    exploded = lite.select("w_id", F.explode("bands").alias("band"))
    candidates = exploded.alias("a") \
        .join(exploded.alias("b"), F.col("a.band") == F.col("b.band")) \
        .filter(F.col("a.w_id") < F.col("b.w_id")) \
        .select(F.col("a.w_id").alias("id1"), F.col("b.w_id").alias("id2")) \
        .distinct()

    # exact jaccard distance on candidate pairs
    pairs = candidates \
        .join(lite.alias("d1"), F.col("id1") == F.col("d1.w_id")) \
        .select("id1", "id2", F.col("d1.indices").alias("ind1"), F.col("d1.t_len").alias("len1")) \
        .join(lite.alias("d2"), F.col("id2") == F.col("d2.w_id")) \
        .select("id1", "id2", "ind1", "len1", F.col("d2.indices").alias("ind2"), F.col("d2.t_len").alias("len2"))

    dupes = pairs \
        .withColumn("inter", F.size(F.array_intersect("ind1", "ind2"))) \
        .withColumn("union_sz", F.size("ind1") + F.size("ind2") - F.col("inter")) \
        .withColumn("jdist", 1.0 - F.col("inter") / F.col("union_sz")) \
        .filter(F.col("jdist") <= 0.5)

    # drop the shorter doc from each duplicate pair
    losers = dupes.select(
        F.when(F.col("len1") >= F.col("len2"), F.col("id2"))
        .otherwise(F.col("id1")).alias("warc_id")
    ).distinct()

    output_df = input_df.join(losers, on="warc_id", how="left_anti")
    df.unpersist()

    ## end your edits here  =================

    return output_df

###!@5a END ANSWER STEP 5a

"""---
## STEP 5b: Exact Deduplication ***(15 points)***
----

### Objective
Remove duplicate documents using exact deduplication using an MD5 fingerprint.

### Reference execution time on Colab & Output Record Count on *Small* Dataset
#### Time: `5 seconds`
#### # of records: `12,949 records`

### Input
- DataFrame with `extracted_text` column (from Step 4)

### Algorithm
1. Calculate the MD5 hash for each record.
2. Retain only one record per hash group.
3. In case of multiple records per group, retain the record with the *earliest* date.


### Output Schema
Same as input (deduplicated records)

### Expected Output Example (Step 5b)
```
root
 |-- warc_id: string (nullable = true)
 |-- url: string (nullable = true)
 |-- date: string (nullable = true)
 |-- extracted_text: string (nullable = true)

[Stage 155:======================================================>(96 + 1) / 97]
+--------------------+--------------------+--------------------+--------------------+
|             warc_id|                 url|                date|      extracted_text|
+--------------------+--------------------+--------------------+--------------------+
|         warc_id_102|http://example.co...|2025-12-04T21:02:54Z|Machine learning ...|
|         warc_id_103|http://example.co...|2025-12-04T21:02:55Z|Python is a high-...|
|<urn:uuid:caa5d51...|https://www.valte...|2025-12-04T20:38:04Z|Agentforce: The G...|
|<urn:uuid:15335f8...|https://www.vande...|2025-12-04T20:39:07Z|This Cookie Polic...|
|<urn:uuid:b5590de...|http://www.elks.o...|2025-12-04T20:06:13Z|Join the Elks!\nL...|
+--------------------+--------------------+--------------------+--------------------+
only showing top 5 rows

Schema Validation Passed!
✓ Step 5b schema validation passed!
```
"""

#######################################
###!@5b START ANSWER STEP 5b

### Q5b ###################################################
def step_5b_deduplication(input_df):
    """
    Args:
        input_df: English text dataframe.
    Returns:
        DataFrame: Deduplicated dataframe.
    """

    ## start your edits here  =================

    # compute MD5 hash for extracted_text
    df_with_hash = input_df.withColumn("md5_hash",F.md5(F.col("extracted_text")))

    # window partitioned by md5_hash and ordered by date
    window_spec = Window.partitionBy("md5_hash").orderBy(F.col("date").asc())

    # assign row number within each hash group
    df_with_rownum = df_with_hash.withColumn("row_num",F.row_number().over(window_spec))

    # keep the first record only
    output_df = (df_with_rownum.filter(F.col("row_num") == 1).drop("md5_hash", "row_num"))

    ## end your edits here  =================

    return output_df

###!@5b END ANSWER STEP 5b

"""---
## STEP 6: Tokenization ***(20 points)***
----

### Objective
Convert cleaned text into *fixed-length* token sequences suitable for LLM training.

### Reference execution time on Colab & Output Record Count on *Small* Dataset
#### Time: `30 seconds (for each of the LSH and MD5)`
#### # of records: `12,808 (LSH) or 12,949 (MD5) records`

### Input
- DataFrame with text column (`extracted_text`, `cleaned_text`, or `text`)

### Guidelines
1. Perform simple word-level tokenization using regex (alphanumeric word boundaries only, ignore punctuation).
2. If extracted_text is null, treat it as an empty string.
3. Each word must be converted into a token ID using the MD5 hashing algorithm from *hashlib* library.
4. As mentioned below, 0 is only for padding (ensure no token ID is 0 and no token ID >= VOCAB_SIZE)
5. If the number of tokens exceeds MAX_LENGTH, truncate the sequence to exactly MAX_LENGTH (pad if less, final length must always be MAX_LENGTH).
6. Generate an attention mask (1 for real token, 0 for padding)

### Tokenization Backends
| Backend | Description |
|---------|-------------|
| `regex` | Word-level tokenization using `\b\w+\b` pattern, hash-based IDs (default) |

### Parameters
| Parameter | Default | Description |
|-----------|---------|-------------|
| max_length | 512 | Maximum sequence length |
| vocab_size | 50000 | Hash space for token IDs |
| pad_id | 0 | Padding token ID |

### Output Schema
| Column | Type | Description |
|--------|------|-------------|
| warc_id | string | Unique WARC record identifier |
| tokens | array<int> | Token IDs (padded to max_length) |
| attention_mask | array<int> | 1 for real tokens, 0 for padding |

### Expected Output Example (Step 6)
```
root
 |-- warc_id: string (nullable = true)
 |-- tokens: array (nullable = true)
 |    |-- element: integer (containsNull = true)
 |-- attention_mask: array (nullable = true)
 |    |-- element: integer (containsNull = true)

+--------------------+--------------------+--------------------+
|             warc_id|              tokens|      attention_mask|
+--------------------+--------------------+--------------------+
|         warc_id_102|[8969, 22291, 342...|[1, 1, 1, 1, 1, 1...|
|<urn:uuid:11e4b22...|[26423, 23563, 48...|[1, 1, 1, 1, 1, 1...|
|<urn:uuid:b929105...|[7260, 111, 9755,...|[1, 1, 1, 1, 1, 1...|
|<urn:uuid:e26e300...|[37479, 10280, 10...|[1, 1, 1, 1, 1, 1...|
|<urn:uuid:d119f3d...|[11201, 47384, 31...|[1, 1, 1, 1, 1, 1...|
+--------------------+--------------------+--------------------+
only showing top 5 rows

Schema Validation Passed!
✓ Step 6 schema validation passed!
```
"""

#######################################
###!@6 START ANSWER STEP 6

### Q6 ###################################################

def step_6_tokenization(input_df):
    """
    Tokenize text. Stdlib-only (no external libs) or sentencepiece.
    Args:
        input_df: Cleaned text dataframe.
    Returns:
        DataFrame: Columns ['warc_id', 'tokens', 'attention_mask']
    """

    ## start your edits here  =================

    # args from v0.2
    backend='regex'
    max_length=512
    vocab_size=50000
    pad_id=0
    model_path=None

    # define schema
    tokenize_schema = StructType([
        StructField('tokens',         ArrayType(IntegerType()), False),
        StructField('attention_mask', ArrayType(IntegerType()), False),
    ])

    # convert a single word string to a deterministic int Id
    def word_to_id(word, vocab_size):
        md5_hex = hashlib.md5(word.encode('utf-8')).hexdigest()   # 32-char hex digest
        return int(md5_hex, 16) % vocab_size                      # map to [0, vocab_size)

    def make_tokenize_udf(backend, max_length, vocab_size, pad_id, model_path):

        def tokenize_fn(text):
            # Guard: null or blank text → all-padding sequence
            # This prevents crashes and marks the row as 'no content'.
            if text is None or text.strip() == '':
                return ([pad_id] * max_length, [0] * max_length)

            # using "regex" backend
            if backend == 'regex':
                words     = re.findall(r'\b\w+\b', text)
                token_ids = [word_to_id(w, vocab_size) for w in words]

            # keep only until max_length
            real_tokens = token_ids[:max_length]
            n_real      = len(real_tokens)        # actual token count (≤ max_length)

            # pad to max_length
            padding_needed = max_length - n_real
            tokens_padded  = real_tokens + [pad_id] * padding_needed

            # create attention_mask
            attention_mask = [1] * n_real + [0] * padding_needed

            return (tokens_padded, attention_mask)

        return F.udf(tokenize_fn, tokenize_schema)

    tokenize_udf = make_tokenize_udf(backend, max_length, vocab_size, pad_id, model_path)

    text_col = None
    for candidate in ('extracted_text'):
        if candidate in input_df.columns:
            text_col = candidate
            break

    if text_col is None:
        raise ValueError("input_df must contain 'extracted_text'")

    # apply udf row by row
    output_df = (input_df.withColumn('result', tokenize_udf(F.col(text_col)))
                         .withColumn('tokens', F.col('result.tokens'))
                         .withColumn('attention_mask', F.col('result.attention_mask')))

    ## end your edits here  =================

    return output_df

###!@6 END ANSWER STEP 6

###!@7 START ANSWER SET EVALUATION
# ========== *** DO NOT MODIFY *** ========== #
from time import time
print(">>> Starting Pipeline Execution...")
t0 = time()
# 1. Convert the warc files to parquet
step_1_warc_to_parquet()

# 2. Parse and url filtering
df_s2 = step_2_ingestion()
validate_step_schema(df_s2, 2)

# 3. Text extraction
df_s3 = step_3_extraction(df_s2)
validate_step_schema(df_s3, 3)

# 4. Language Identification
df_s4 = step_4_lang_id(df_s3)
validate_step_schema(df_s4, 4)

# 5a. Deduplication (LSH)
df_s5a = step_5a_deduplication(df_s4)
validate_step_schema(df_s5a, 5)

# 5b. Deduplication (MD5)
df_s5b = step_5b_deduplication(df_s4)
validate_step_schema(df_s5b, 5)

# 6. Tokenization
df_final_a = step_6_tokenization(df_s5a)
validate_step_schema(df_final_a, 6)

# 6. Tokenization
df_final_b = step_6_tokenization(df_s5b)
validate_step_schema(df_final_b, 6)


print(f"E2E time: {time() - t0:.2f}s")
# ========== *** DO NOT MODIFY *** ========== #
###!@7 END ANSWER SET EVALUATION